# Generated by Django 2.2.7 on 2019-11-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchQuery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='books/pdfs/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='books/covers/')),
            ],
        ),
        migrations.AlterField(
            model_name='searchbar',
            name='query',
            field=models.TextField(),
        ),
    ]
