# Generated by Django 2.2.7 on 2019-11-30 08:46

from django.db import migrations, models
import searchQuery.validators


class Migration(migrations.Migration):

    dependencies = [
        ('searchQuery', '0002_auto_20191129_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentDetails',
            fields=[
                ('id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('abstract', models.TextField()),
                ('authors', models.TextField()),
                ('title', models.TextField()),
                ('references', models.TextField()),
                ('venue', models.TextField()),
                ('n_citation', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(upload_to='books/pdfs/', validators=[searchQuery.validators.validate_file_extension]),
        ),
    ]
